// https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 
// terms will be: 1,2,3,5,8,13,21,34,55,89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class Main {
    public static void main(String[] args) {
        
        int i = 1, j = 2, n = 4000000, sum = 0; int[] arr = new int[n];
        for(int k = 0; k<n; k++){
            if (k == 0 ){
                arr[0]=i;
            }else if (k == 1 ){
                arr[1]=j;
            }else if (k == 2 ){
                arr[2]=i+j;
            }
            if(k>2){
                if (arr[k-1]+arr[k-2] > 4000000){
                    break;
                }
                arr[k]=arr[k-1]+arr[k-2];
            }
            if(arr[k]%2==0){
                sum += arr[k];
            }
        }
        // for(int l=0; l<n;l++){
        //     System.out.println(arr[l]);
        // }
        System.out.println("sum = "+sum);
    }
}
